-- Create type for ticket status
CREATE TYPE public.ticket_status AS ENUM
    ('Open', 'In Progress', 'Closed');

-- Create the ticket table
CREATE TABLE IF NOT EXISTS public.ticket (
    ticket_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_id INTEGER NOT NULL,
    ticket_subject VARCHAR(100) NOT NULL,
    ticket_description TEXT NOT NULL,
    ticket_status ticket_status NOT NULL DEFAULT 'Open'::ticket_status,
    ticket_created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ticket_updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ticket_pkey PRIMARY KEY (ticket_id),
    CONSTRAINT ticket_account_fk FOREIGN KEY (account_id)
        REFERENCES public.account (account_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);
