-- Drop the ticket_status type if it exists
DROP TYPE IF EXISTS public.ticket_status;

-- Create ticket_status enum type
CREATE TYPE public.ticket_status AS ENUM ('Open', 'In Progress', 'Closed');

-- Create ticket table
CREATE TABLE IF NOT EXISTS public.ticket (
    ticket_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_id integer NOT NULL,
    ticket_subject character varying(100) NOT NULL,
    ticket_description text NOT NULL,
    ticket_status ticket_status NOT NULL DEFAULT 'Open'::ticket_status,
    ticket_created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    ticket_updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ticket_pkey PRIMARY KEY (ticket_id),
    CONSTRAINT ticket_account_fk FOREIGN KEY (account_id)
        REFERENCES public.account (account_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- Add some sample tickets for testing
INSERT INTO public.ticket (account_id, ticket_subject, ticket_description, ticket_status)
SELECT 
    a.account_id,
    'Test Ticket',
    'This is a test ticket to verify the system is working.',
    'Open'::ticket_status
FROM public.account a
LIMIT 1;
